## Scaling of data using scikit-learn

[scikit-learn](https://scikit-learn.org/) is a very helpful Open-source, commercial usable machine learning library. It comes with a so called [`MinMaxScaler`](https://scikit-learn.org/stable/modules/preprocessing.html#scaling-features-to-a-range) that allows to scale features to a certain range.

by Prof. Dr.-Ing. Jürgen Brauer, www.juergenbrauer.org

## 1. Prepare some example data to scale

In [3]:
import numpy as np
data = np.array([ [10.0, 20.0],
                  [15.0, 40.0],
                  [20.0, 60.0]])
print(data)
print("Type of data is", type(data))

[[10. 20.]
 [15. 40.]
 [20. 60.]]
Type of data is <class 'numpy.ndarray'>


## 2. Scale the data to a certain range

In [4]:
from sklearn.preprocessing import MinMaxScaler

# 2. create a MinMaxScaler with feature range [0,1]
scaler = MinMaxScaler(feature_range=(0, 1))
transformed_data = scaler.fit_transform(data)
print(transformed_data)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


## 3. Now use the scaler to transform new data

In [6]:
data2 = np.array( [[10.0, 20.0],
                   [20.0, 60.0],
                   [30.0, 100.0]])
transformed_data2 = scaler.transform(data2)
print(transformed_data2)

[[0. 0.]
 [1. 1.]
 [2. 2.]]


## 4. Use the scaler to undo a transformation

In [7]:
print(transformed_data)
original_data = scaler.inverse_transform(transformed_data)
print(original_data)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]
[[10. 20.]
 [15. 40.]
 [20. 60.]]
