<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction:-TensorFlow-datasets" data-toc-modified-id="Introduction:-TensorFlow-datasets-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction: TensorFlow datasets</a></span></li><li><span><a href="#Check-TensorFlow-version" data-toc-modified-id="Check-TensorFlow-version-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Check TensorFlow version</a></span></li><li><span><a href="#Creating-a-TF-dataset" data-toc-modified-id="Creating-a-TF-dataset-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Creating a TF dataset</a></span></li><li><span><a href="#The-take()-method" data-toc-modified-id="The-take()-method-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>The <code>take()</code> method</a></span></li><li><span><a href="#The-batch()-method" data-toc-modified-id="The-batch()-method-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>The <code>batch()</code> method</a></span></li><li><span><a href="#The-unbatch()-method" data-toc-modified-id="The-unbatch()-method-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>The <code>unbatch()</code> method</a></span></li><li><span><a href="#The-shuffle()-method" data-toc-modified-id="The-shuffle()-method-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>The <code>shuffle()</code> method</a></span></li><li><span><a href="#The-map()-method" data-toc-modified-id="The-map()-method-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>The <code>map()</code> method</a></span></li><li><span><a href="#The-filter()-method" data-toc-modified-id="The-filter()-method-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>The <code>filter()</code> method</a></span></li><li><span><a href="#The-repeat()-method" data-toc-modified-id="The-repeat()-method-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>The <code>repeat()</code> method</a></span></li></ul></div>

# Introduction: TensorFlow datasets

The TF dataset class is used to
- store large amount of data
- get data samples from the dataset in different forms

# Check TensorFlow version

In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0


# Creating a TF dataset

In [4]:
ds1 = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6,7,8,9])

In [5]:
type(ds1)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [6]:
for data in ds1:
    print(data)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [8]:
ds2 = tf.data.Dataset.from_tensor_slices([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
for data in ds2:
    print(data)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)


# The `take()` method

In [29]:
for data in ds1.take(2):
    print(data)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [33]:
for data in ds1.take(5):
    print(data)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


# The `batch()` method

In [11]:
ds3 = tf.data.Dataset.\
      from_tensor_slices([1,2,3,4,5,6,7,8,9]).batch(batch_size=3)

In [12]:
for data in ds3:
    print(data)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)


In [13]:
ds3 = tf.data.Dataset.\
      from_tensor_slices([1,2,3,4,5,6,7,8,9]).batch(batch_size=4)

In [14]:
for data in ds3:
    print(data)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor([9], shape=(1,), dtype=int32)


# The `unbatch()` method

In [15]:
ds4 = tf.data.Dataset.from_tensor_slices([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
for data in ds4:
    print(data)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)


In [20]:
for data in ds4.unbatch():
    print(data)    

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


# The `shuffle()` method

In [21]:
ds5 = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6,7,8,9])

In [22]:
for data in ds5:
    print(data)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


From the TF website:

>This dataset fills a buffer with buffer_size elements, then randomly samples elements from this buffer, replacing the selected elements with new elements. For perfect shuffling, a buffer size greater than or equal to the full size of the dataset is required.

>For instance, if your dataset contains 10,000 elements but buffer_size is set to 1,000, then shuffle will initially select a random element from only the first 1,000 elements in the buffer. Once an element is selected, its space in the buffer is replaced by the next (i.e. 1,001-st) element, maintaining the 1,000 element buffer.

In [28]:
for data in ds5.shuffle(buffer_size=10):
    print(data)

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


# The `map()` method

In [35]:
import numpy as np
ds6 = tf.data.Dataset.from_tensor_slices( np.arange(1,10) )

In [36]:
for data in ds6:
    print(data)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [37]:
def preprocess_data(x):
    return x**2

In [39]:
for data in ds6.map(preprocess_data):
    print(data)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(49, shape=(), dtype=int32)
tf.Tensor(64, shape=(), dtype=int32)
tf.Tensor(81, shape=(), dtype=int32)


In [40]:
for data in ds6.batch(batch_size=3).map(preprocess_data):
    print(data)

tf.Tensor([1 4 9], shape=(3,), dtype=int32)
tf.Tensor([16 25 36], shape=(3,), dtype=int32)
tf.Tensor([49 64 81], shape=(3,), dtype=int32)


# The `filter()` method

In [57]:
import numpy as np
ds7 = tf.data.Dataset.from_tensor_slices( np.arange(1,20) )

In [58]:
def filter_predicate(x):
    if x % 2 == 0:
        return True
    else:
        return False

In [59]:
for data in ds7.filter(filter_predicate):
    print(data)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)


# The `repeat()` method

In [61]:
import numpy as np
ds7 = tf.data.Dataset.from_tensor_slices( np.arange(1,6) )

In [62]:
for data in ds7.repeat(3):
    print(data)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
