<h1>Inhaltsverzeichnis<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Einleitung" data-toc-modified-id="Einleitung-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Einleitung</a></span></li><li><span><a href="#Eine-Perzeptronschicht" data-toc-modified-id="Eine-Perzeptronschicht-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Eine Perzeptronschicht</a></span></li><li><span><a href="#Mehrere-Schichten-zu-einem-Multi-Layer-Perzeptron-zusammensetzen" data-toc-modified-id="Mehrere-Schichten-zu-einem-Multi-Layer-Perzeptron-zusammensetzen-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Mehrere Schichten zu einem Multi-Layer Perzeptron zusammensetzen</a></span></li><li><span><a href="#Ein-Feedforward-Schritt" data-toc-modified-id="Ein-Feedforward-Schritt-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Ein Feedforward-Schritt</a></span></li><li><span><a href="#Testen,-ob-das-MLP-richtig-rechnet" data-toc-modified-id="Testen,-ob-das-MLP-richtig-rechnet-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Testen, ob das MLP richtig rechnet</a></span></li></ul></div>

# Einleitung

Den Vorwärtsschritt eines MLPs zu implementieren ist nicht kompliziert. Das soll dieses Jupyter Notebook zeigen.

# Eine Perzeptronschicht

In [47]:
import numpy as np
from random import randint

# RELU
def f(x):
    if x < 0.0:
        return 0.0
    else:
        return x
    
f = np.vectorize(f)

def create_new_perceptron(nr_inputs, nr_outputs):
    low = -1
    high = +1
    bias_input = 1
    W = np.random.uniform(low,high, (nr_inputs+bias_input, nr_outputs) )
    return W

def predict(W,x):
    x_with_bias = np.append(x,[1.0])
    act = np.matmul(x_with_bias, W)
    out = f(act)
    return out

# Mehrere Schichten zu einem Multi-Layer Perzeptron zusammensetzen

In [48]:
nr_inputs = 784
nr_hidden1 = 100
nr_hidden2 = 25
nr_outputs = 10

In [49]:
W1 = create_new_perceptron(nr_inputs,nr_hidden1)

In [50]:
W1.shape

(785, 100)

In [51]:
W1

array([[ 0.17970019,  0.04730199,  0.16197029, ...,  0.36503661,
        -0.13975744, -0.16192332],
       [-0.55348795, -0.87826801,  0.40773975, ...,  0.25488725,
        -0.35990648, -0.04375535],
       [-0.450479  , -0.01631502, -0.32322278, ...,  0.78929776,
         0.48899307,  0.18346241],
       ..., 
       [-0.89198726,  0.99592803, -0.22785526, ...,  0.74483429,
        -0.20757338,  0.61099295],
       [ 0.39258126,  0.43651452, -0.06137812, ..., -0.03693401,
         0.75123778, -0.51874089],
       [-0.67374188, -0.60380356,  0.23314979, ..., -0.62090501,
        -0.95009144, -0.44878915]])

In [52]:
W2 = create_new_perceptron(nr_hidden1, nr_hidden2)

In [53]:
W2.shape

(101, 25)

In [54]:
W3 = create_new_perceptron(nr_hidden2, nr_outputs)

In [55]:
W3.shape

(26, 10)

In [56]:
W1.size

78500

In [57]:
nr_params = W1.size+W2.size+W3.size

In [58]:
nr_params

81285

# Ein Feedforward-Schritt

In [59]:
x = np.ones(784)

In [60]:
x[:10]

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [61]:
y1 = predict(W1,x)

In [62]:
y1.shape

(100,)

In [63]:
y1

array([  0.        ,   0.        ,   0.        ,   0.        ,
        20.08852199,   5.02009473,   0.        ,   0.        ,
         0.74754486,   0.        ,   0.        ,   3.30960782,
         7.98669607,   0.        ,   0.        ,  12.00390724,
         0.        ,   2.99901936,   0.30361848,   0.        ,
         0.        ,   2.26955867,   9.91087627,   1.8526322 ,
         9.76666001,   0.        ,   0.        ,  12.83898342,
         0.        ,   0.        ,   0.        ,   0.        ,
         2.44674318,   0.        ,   0.        ,  13.26191557,
         0.        ,   0.        ,  16.25497103,  12.62465198,
         5.57821979,  13.93865136,   3.06310243,   3.67745757,
         0.        ,   0.        ,   0.        ,   0.        ,
        11.95505195,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,  19.93404467,  34.40937934,
        13.0551871 ,   3.54666891,   0.        ,   0.        ,
         0.05575272,   0.        ,  16.24786072,   7.80

In [64]:
y2 = predict(W2,y1)

In [65]:
y2.shape

(25,)

In [66]:
y3 = predict(W3,y2)

In [67]:
y3

array([   0.        ,    0.        ,   51.62769581,  236.97876377,
          0.        ,  170.62148104,    0.        ,    0.        ,
          0.        ,    0.        ])

# Testen, ob das MLP richtig rechnet

In [72]:
W1 = np.ones( (nr_inputs +1, nr_hidden1) )
W2 = np.ones( (nr_hidden1+1, nr_hidden2) )
W3 = np.ones( (nr_hidden2+1, nr_outputs) )
x = np.ones(784)

In [73]:
y1 = predict(W1,x)

In [74]:
y1

array([ 785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,
        785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,
        785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,
        785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,
        785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,
        785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,
        785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,
        785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,
        785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,
        785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,
        785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.,  785.])

In [75]:
y2 = predict(W2,y1)

In [76]:
y2

array([ 78501.,  78501.,  78501.,  78501.,  78501.,  78501.,  78501.,
        78501.,  78501.,  78501.,  78501.,  78501.,  78501.,  78501.,
        78501.,  78501.,  78501.,  78501.,  78501.,  78501.,  78501.,
        78501.,  78501.,  78501.,  78501.])

In [77]:
y3 = predict(W3,y2)

In [78]:
y3

array([ 1962526.,  1962526.,  1962526.,  1962526.,  1962526.,  1962526.,
        1962526.,  1962526.,  1962526.,  1962526.])